language: c++
# Enable trusty so we have access to libmetis-dev
sudo: required
dist: trusty
# Install various library dependencies and mroe up-to-date compilers
addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
      packages:
         - libmetis-dev
         - libatlas-dev
         - liblapack-dev
# Make OpenMP happy
env:
   global:
      - OMP_NESTED=true
      - OMP_CANCELLATION=true
      - OMP_PROC_BIND=true
      - OMP_NUM_THREADS=4
# Define matrix of builds with different compiler versions
matrix:
   include:
      - compiler: gcc
        addons:
           apt:
              packages:
                 - gfortran-5
                 - gcc-5
                 - g++-5
        env: CC=gcc-5 CXX=g++-5 FC=gfortran-5
      - compiler: gcc
        addons:
           apt:
              packages:
                 - gfortran-6
                 - gcc-6
                 - g++-6
        env: CC=gcc-6 CXX=g++-6 FC=gfortran-6
# Don't worry about high git depth, we don't need it
git:
   depth: 3
# Pre build, generate autotools files
install:
   - ./autogen.sh
# Actual build step
script:
   - ./configure && make && make check
